# Generated by Django 6.0.6 on 2026-06-25 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('horas_sueno', models.FloatField(help_text='Horas de sueño de la noche anterior')),
                ('fatiga_muscular', models.IntegerField(help_text='Nivel de fatiga muscular del 1 al 10')),
                ('nivel_estres', models.IntegerField(help_text='Nivel de estrés del 1 al 10')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_recuperacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metricas_recuperacion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Wod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrenamiento', models.DateField(auto_now_add=True)),
                ('nombre_ejercicio', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('for_time', 'For Time (Por Tiempo)'), ('amrap', 'AMRAP (As Many Rounds As Possible)'), ('emom', 'EMOM (Every Minute On the Minute)'), ('tabata', 'Tabata / Intervalos')], max_length=20)),
                ('resultado_repeticiones', models.IntegerField(blank=True, null=True)),
                ('resultado_tiempo', models.FloatField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WODs',
                'ordering': ['-fecha_entrenamiento'],
            },
        ),
    ]
